Models/Entity/Musteri.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcStok.Models.Entity
{
    public class Musteri
    {
        [Key]
        public int MusteriId { get; set; }
        [Required]
        public string MusteriAd { get; set; }
        [Required]
        public string MusteriSoyad { get; set; }
    }
}

Controllers/MusteriController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MvcStok.Data;
using MvcStok.Models.Entity;
using NuGet.Protocol.Core.Types;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        private readonly StokDbContext _context;
        public MusteriController(StokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var musteri=_context.Musteriler.ToList();
            return View(musteri);
        }
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Musteri model)
        {
            if(ModelState.IsValid)
            {
                _context.Musteriler.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        public IActionResult Kaldir(int id)
        {
            var musteri = _context.Musteriler.Find(id);
            if(musteri is not null)
            {
                _context.Remove(musteri);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Guncelle(int id)
        {
            var musteri=_context.Musteriler.Find(id);
            return View("Guncelle", musteri);
        }
        [HttpPost]
        public IActionResult Guncelle(int id,Musteri model)
        {
            var musteri = _context.Musteriler.Find(id);
            if (ModelState.IsValid)
            {
                musteri.MusteriAd = model.MusteriAd;
                musteri.MusteriSoyad = model.MusteriSoyad;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(model);
        }

    }
}

Views/Musteri/Ekle.cshtml
@using MvcStok.Models.Entity
@model Musteri;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Ekle", "Musteri", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Müşteri Ekle</h3>
                    <br />
                    @Html.LabelFor(m => m.MusteriAd,"Müşteri Adı : ")
                    @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.MusteriSoyad,"Müşteri Soyadı :")
                    @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control" })
                    <br /><br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Musteri/Guncelle.cshtml
@using MvcStok.Models.Entity

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @model Musteri;

            @using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Müşteri Güncelle</h3>

                    @Html.LabelFor(m => m.MusteriAd, "Müşteri Adı:")
                    @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.MusteriSoyad, "Müşteri Soyadı:")
                    @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control" })
                    <br />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Musteri>;
<h2>Müşteriler</h2>
<table class="table">
    <tr>
        <th scope="col" colspan="2">#</th>
        <th scope="col" colspan="2">Ad</th>
        <th scope="col" colspan="2">Soyad</th>
        <th scope="col">Düzenle</th>
        <th scope="col">Kaldır</th>
    </tr>

    @foreach (var musteri in Model)
    {
        <tr>
            <th scope="row" colspan="2">@musteri.MusteriId</th>
            <td colspan="2">@musteri.MusteriAd</td>
            <td colspan="2">@musteri.MusteriSoyad</td>
            <td><a class="btn btn-primary" asp-action="Guncelle" asp-route-id="@musteri.MusteriId">Güncelle</a></td>
            <td><a class="btn btn-warning" asp-action="Kaldir" asp-route-id="@musteri.MusteriId">Kaldır</a></td>

        </tr>
    }
</table>
<p>Toplam @Model.Count Müşteri bulunuyor</p>
<a class="btn btn-primary" asp-action="Ekle">Müşteri Ekle</a>