Models/Entity/Urun.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcStok.Models.Entity
{
    public class Urun
    {
        [Key]
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public int UrunKategori { get; set; }
        public decimal Fiyat { get; set; }
        public int Stok { get; set; }
    }
}

Models/ViewModels/UrunViewModel.cs
namespace MvcStok.Models.ViewModels
{
    public class UrunViewModel
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Kategori { get; set; }
        public decimal Fiyat { get; set; }
        public int Stok { get; set; }
    }
}

Controllers/UrunController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcStok.Data;
using MvcStok.Models.Entity;
using MvcStok.Models.ViewModels;

namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        private readonly StokDbContext _context;
        public UrunController(StokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<UrunViewModel> vm = (from u in _context.Urunler.ToList()
                                      join k in _context.Kategoriler.ToList()
                                      on u.UrunKategori equals k.KategoriId
                                      select new UrunViewModel
                                      {
                                          Id = u.UrunId,
                                          Ad = u.UrunAd,
                                          Kategori = k.KategoriAd,
                                          Fiyat = u.Fiyat,
                                          Stok = u.Stok
                                      }).ToList();   
            return View(vm);
        }
        public IActionResult Ekle()
        {
            List<SelectListItem> degerler = (from i in _context.Kategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoriAd,
                                                 Value = i.KategoriId.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Urun model)
        {
            if (ModelState.IsValid)
            {
                _context.Urunler.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(model);
        }
        public IActionResult Kaldir(int id)
        {
            var urun = _context.Urunler.Find(id);
            if(urun is not null)
            {
                _context.Remove(urun);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Guncelle(int id)
        {
            var urun = _context.Urunler.Find(id);
            List<SelectListItem> degerler = (from i in _context.Kategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoriAd,
                                                 Value = i.KategoriId.ToString()
                                             }).ToList();
            ViewBag.urun = degerler;
            return View("Guncelle", urun);
        }
        [HttpPost]
        public IActionResult Guncelle(int id,Urun model)
        {
            var urun = _context.Urunler.Find(id);
            if (ModelState.IsValid)
            {
                urun.UrunAd = model.UrunAd;
                urun.UrunKategori = model.UrunKategori;
                urun.Fiyat = model.Fiyat;
                urun.Stok = model.Stok;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Views/Urun/Ekle.cshtml
@using MvcStok.Models.Entity
@model Urun;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Ekle", "Urun", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Ürün Ekle</h3>

                    @Html.LabelFor(m => m.UrunAd, "Ürün Adı:")
                    @Html.TextBoxFor(m => m.UrunAd, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.UrunKategori, "Ürün Kategorisi:")
                    @Html.DropDownListFor(m=>m.UrunKategori,(List<SelectListItem>)ViewBag.dgr,new {@class="form-control"})
                    <br />
                    @Html.LabelFor(m => m.Stok, "Ürün Stoğu:")
                    @Html.TextBoxFor(m => m.Stok, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Fiyat, "Ürün Fiyatı:")
                    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                    <br />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Urun/Guncelle.cshtml
@using MvcStok.Models.Entity
@model Urun;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
           

            @using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Ürün Güncelle</h3>

                    @Html.LabelFor(m => m.UrunAd, "Ürün Adı:")
                    @Html.TextBoxFor(m => m.UrunAd, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.UrunKategori, "Ürün Kategorisi:")
                    @Html.DropDownListFor(m => m.UrunKategori, (List<SelectListItem>)ViewBag.urun, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Stok, "Ürün Stoğu:")
                    @Html.TextBoxFor(m => m.Stok, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Fiyat, "Ürün Fiyatı:")
                    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                    <br />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Urun/Index.cshtml
@using MvcStok.Models.ViewModels
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<UrunViewModel>;
<h2>Ürünler</h2>

<table class="table">
    <tr>
        <th scope="col" colspan="2">#</th>
        <th scope="col" colspan="2">Ürün Adı</th>
        <th scope="col" colspan="2">Ürün Kategorisi</th>
        <th scope="col" colspan="2">Ürün Stoğu</th>
        <th scope="col" colspan="2">Ürün Fiyatı</th>
        <th scope="col">Düzenle</th>
        <th scope="col">Kaldır</th>
    </tr>

    @foreach (var urun in Model)
    {
        <tr>
            <th scope="row" colspan="2">@urun.Id</th>
            <td colspan="2">@urun.Ad</td>
            <td colspan="2">@urun.Kategori</td>
            <td colspan="2">@urun.Stok</td>
            <td colspan="2">@{var a=urun.Fiyat + " ₺";}@a</td>
            <td><a class="btn btn-primary" asp-action="Guncelle" asp-route-id="@urun.Id">Güncelle</a></td>
            <td><a class="btn btn-warning" asp-action="Kaldir" asp-route-id="@urun.Id">Kaldır</a></td>
        </tr>
    }
</table>
<p>Toplam @Model.Count Ürün bulunuyor</p>
<a class="btn btn-primary" asp-action="Ekle">Ürün Ekle</a>
<h2>Yakında Gelecek Ürünler</h2>
@await Component.InvokeAsync("YeniUrunler")