Models/Entity/Kategori.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcStok.Models.Entity
{
    public class Kategori
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int KategoriId { get; set; }
        [Required]
        public string KategoriAd { get; set; }
    }
}

Controllers/KategoriController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcStok.Data;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        private readonly StokDbContext _context;
        public KategoriController(StokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var kategori=_context.Kategoriler.ToList();
            return View(kategori);
        }
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Kategori model)
        {
            if (ModelState.IsValid)
            {
                _context.Kategoriler.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult Kaldir(int id)
        {
            var kategori = _context.Kategoriler.Find(id);
            if(kategori is not null)
            {
                _context.Kategoriler.Remove(kategori);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Guncelle(int id)
        {
            var kategori = _context.Kategoriler.Find(id);
            return View("Guncelle",kategori);
        }
        [HttpPost]
        public IActionResult Guncelle(int id,Kategori model)
        {
            var kategori = _context.Kategoriler.Find(id);
            
            if (ModelState.IsValid)
            {
                kategori.KategoriAd=model.KategoriAd;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View("Getir");
        }
    }
}

Views/Kategori/Ekle.cshtml
@using MvcStok.Models.Entity
@model Kategori;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Ekle", "Kategori", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Kategori Ekle</h3>
                    <br />
                    @Html.LabelFor(m => m.KategoriAd,"Kategori Adı : ")
                    @Html.TextBoxFor(m => m.KategoriAd, new { @class = "form-control" })
                    <br /><br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Kategori/Guncelle.cshtml
@using MvcStok.Models.Entity

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Kategori;
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(m=>m.KategoriAd)
                    @Html.TextBoxFor(m=>m.KategoriAd,new{@class="form-control"})
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Kategori>;
<h2>Kategoriler</h2>
<table class="table">
    <tr>
        <th scope="col" colspan="2">#</th>
        <th scope="col" colspan="2">Kategori Adı</th>
        <th scope="col">Düzenle</th>
        <th scope="col">Kaldır</th>
    </tr>

@foreach(var kategori in Model)
{
   <tr>
       <th scope="row" colspan="2">@kategori.KategoriId</th>
       <td colspan="2">@kategori.KategoriAd</td>
       <td><a class="btn btn-primary"asp-action="Guncelle" asp-route-id="@kategori.KategoriId">Güncelle</a></td>
       <td><a class="btn btn-warning"asp-action="Kaldir" asp-route-id="@kategori.KategoriId">Kaldır</a></td>

   </tr>
}
</table>
<p>Toplam @Model.Count Kategori bulunuyor</p>
<a class="btn btn-primary" asp-action="Ekle">Kategori Ekle</a>