Models/Entity/Satis.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcStok.Models.Entity
{ 
    public class Satis
    {
        [Key]
        public int SatisId { get; set; }
        public int Urun { get; set; }
        public int Musteri { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
    }
}

Models/ViewModels/SatisViewModel.cs
namespace MvcStok.Models.ViewModels
{
    public class SatisViewModel
    {
        public int Id { get; set; }
        public string Urun { get; set; }
        public string Musteri { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
    }
}

Controllers/SatisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcStok.Data;
using MvcStok.Models.Entity;
using MvcStok.Models.ViewModels;
namespace MvcStok.Controllers
{
    public class SatisController : Controller
    {
        private readonly StokDbContext _context;
        public SatisController(StokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int sayfa=0)
        {

            List<SatisViewModel> vm = (from s in _context.Satislar.ToList()
                                       join u in _context.Urunler.ToList()
                                       on s.Urun equals u.UrunId
                                       join m in _context.Musteriler.ToList()
                                       on s.Musteri equals m.MusteriId
                                       select new SatisViewModel
                                       {
                                           Id = s.SatisId,
                                           Urun = u.UrunAd,
                                           Musteri = m.MusteriAd + " " + m.MusteriSoyad,
                                           Adet = s.Adet,
                                           Fiyat = s.Fiyat
                                       }).ToList();
            return View(vm);
        }
        public IActionResult Ekle()
        {
            List<SelectListItem> musteriler = (from i in _context.Musteriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.MusteriAd + " " + i.MusteriSoyad,
                                                 Value = i.MusteriId.ToString()
                                             }).ToList();
            List<SelectListItem> urunler = (from i in _context.Urunler.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.UrunAd + " |" + i.Fiyat.ToString()+ "₺"+" | Stok:"+i.Stok.ToString(),
                                                Value = i.UrunId.ToString()
                                            }).ToList();
            ViewBag.urunler = urunler;
            ViewBag.musteriler = musteriler;
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Satis model)
        {
            if (ModelState.IsValid)
            {
                _context.Satislar.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(model);
        }
        public IActionResult Kaldir(int id)
        {
            var satis = _context.Satislar.Find(id);
            if(satis is not null)
            {
                _context.Satislar.Remove(satis);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public IActionResult Guncelle(int id)
        {
            var satis = _context.Satislar.Find(id);
            List<SelectListItem> urunler = (from i in _context.Urunler.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.UrunAd + " | " + i.Fiyat.ToString() + "₺" + " | Stok:" + i.Stok.ToString(),
                                                Value = i.UrunId.ToString()
                                            }).ToList();
            List<SelectListItem> musteriler = (from i in _context.Musteriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.MusteriAd+" "+i.MusteriSoyad,
                                                 Value = i.MusteriId.ToString()
                                             }).ToList();
            ViewBag.Surun = urunler;
            ViewBag.Smusteri = musteriler;
            return View("Guncelle", satis);
        }
        [HttpPost]
        public IActionResult Guncelle(int id, Satis model)
        {
            var satis = _context.Satislar.Find(id);
            if (ModelState.IsValid)
            {
                satis.Urun = model.Urun;
                satis.Musteri = model.Musteri;
                satis.Adet = model.Adet;
                satis.Fiyat = model.Fiyat;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Views/Satis/Ekle.cshtml
@using MvcStok.Models.Entity
@model Satis;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Ekle", "Satis", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Satış Ekle</h3>

                    @Html.LabelFor(m => m.Urun, "Ürün :")
                    @Html.DropDownListFor(m => m.Urun, (List<SelectListItem>)ViewBag.urunler, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Musteri, "Müşteri:")
                    @Html.DropDownListFor(m => m.Musteri, (List<SelectListItem>)ViewBag.musteriler, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Adet, "Adet :")
                    @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Fiyat, "Fiyat:")
                    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                    <br />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Satis/Guncelle.cshtml
@using MvcStok.Models.Entity
@model Satis;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @using (Html.BeginForm("Guncelle", "Satis", FormMethod.Post))
            {
                <div class="form-group">
                    <h3>Satış Güncelle</h3>

                    @Html.LabelFor(m => m.Urun, "Ürün :")
                    @Html.DropDownListFor(m=>m.Urun,(List<SelectListItem>)ViewBag.Surun,new{@class="form-control"})
                    <br />
                    @Html.LabelFor(m => m.Musteri, "Müşteri :")
                    @Html.DropDownListFor(m => m.Musteri, (List<SelectListItem>)ViewBag.Smusteri, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Adet, "Adet :")
                    @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Fiyat, "Fiyat :")
                    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                    <br />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Satis/Index.cshtml
@using MvcStok.Models.ViewModels
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<SatisViewModel>;
<h2>Satışlar</h2>

<table class="table">
    <tr>
        <th scope="col" colspan="2">#</th>
        <th scope="col" colspan="2">Ürün</th>
        <th scope="col" colspan="2">Müşteri</th>
        <th scope="col" colspan="2">Adet</th>
        <th scope="col" colspan="2">Fiyat</th>
        <th scope="col">Düzenle</th>
        <th scope="col">Kaldır</th>
    </tr>

    @foreach (var satis in Model)
    {
        <tr>
            <th scope="row" colspan="2">@satis.Id</th>
            <td colspan="2">@satis.Urun</td>
            <td colspan="2">@satis.Musteri</td>
            <td colspan="2">@satis.Adet</td>
            <td colspan="2">@satis.Fiyat</td>
            <td><a class="btn btn-primary" asp-action="Guncelle" asp-route-id="@satis.Id">Güncelle</a></td>
            <td><a class="btn btn-warning" asp-action="Kaldir" asp-route-id="@satis.Id">Kaldır</a></td>
        </tr>
    }
</table>
<p>Toplam @Model.Count Satış bulunuyor</p>
<a class="btn btn-primary" asp-action="Ekle">Satış Ekle</a>